# Generated by Django 5.2.3 on 2025-06-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="chatgroup",
            table="Group Chats",
        ),
        migrations.AlterModelTable(
            name="groupmessages",
            table="Group Messages",
        ),
    ]
