# Generated by Django 5.2.3 on 2025-06-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_alter_chatgroup_table_alter_groupmessages_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="chatgroup",
            table="Chat Groups",
        ),
    ]
