# Generated by Django 5.2.3 on 2025-06-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_alter_chatgroup_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatgroup",
            options={"verbose_name_plural": "Chat Groups"},
        ),
        migrations.AlterModelOptions(
            name="groupmessages",
            options={
                "ordering": ["-timestamp"],
                "verbose_name_plural": "Group Messages",
            },
        ),
        migrations.AlterModelTable(
            name="chatgroup",
            table=None,
        ),
        migrations.AlterModelTable(
            name="groupmessages",
            table=None,
        ),
    ]
