# Generated by Django 5.2.3 on 2025-06-16 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_alter_chatgroup_options_alter_groupmessages_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmessages",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages_rel",
                to="chats.chatgroup",
            ),
        ),
    ]
